"""added last search

Revision ID: 9fee0c23b437
Revises: 189a6af93384
Create Date: 2018-04-20 20:19:35.588892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fee0c23b437'
down_revision = '189a6af93384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_search', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_search')
    # ### end Alembic commands ###
