"""added images fields

Revision ID: b42e59907150
Revises: cbe6b840cb1c
Create Date: 2018-04-08 13:32:12.068253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42e59907150'
down_revision = 'cbe6b840cb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('image_filename', sa.String(length=140), nullable=True))
    op.add_column('event', sa.Column('image_url', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'image_url')
    op.drop_column('event', 'image_filename')
    # ### end Alembic commands ###
