"""added event category

Revision ID: cbe6b840cb1c
Revises: b920bb10a34b
Create Date: 2018-03-23 23:29:19.383629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe6b840cb1c'
down_revision = 'b920bb10a34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('category', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'category')
    # ### end Alembic commands ###
